CREATE TABLE Station
(
    ST1      VARCHAR2(20),
    ST2      VARCHAR2(20),
    ALTNAME  VARCHAR2(30),
    DOCKS    INT
);

INSERT INTO Station (ST1,ST2,DOCKS) VALUES 
    ('Lankershim','Califa',10),('Chandler','Laurel Canyon',15),('Chandler','Colfax',18),('Chandler','Cahuenga',12),('Magnolia','Cartwright',12),
    ('Magnolia','Clybourn',11),('Lankershim','Hesby',11),('Lankershim','Vineland',12),('Riverside','Cahuenga',18),('Mariota','Riverside',13),
    ('Franklin','Fuller',22),('Yucca','Argyle',23),('Highland','Hollywood',11),('McCadden','Hollywood',14),('Whitley','Hollywood',13),
    ('Ivar','Hollywood',15),('Argyle','Hollywood',17),('Hawthorn','Orange',11),('Highland','Sunset',23),('Wilcox','Fountain',15),
    ('Fountain','Vine',14),('Western','Hollywood',10),('Normandie','Hollywood',14),('Normandie','Sunset',9),('Ambrose','Hillhurst',9),
    ('Rowena','Hyperion',18),('Vermont','Franklin',9),('Franklin','Hillhurst',13),('Tracy','Hyperion',13),('Glendale','Silver Lake',12),
    ('Melbourne','Vermont',10),('Hillhurst','Kingswell',10),('Hollywood','Rodney',8),('Maubert','Vermont',10),('Sunset','Virgil',10),
    ('Hoover','Mountain',13),('Vermont Pl','Vermont',10),('Santa Monica','Sunset',17),('Santa Monica','Virgil',14),('Edgemont','Melrose',18),
    ('Lucile','Hoover',6),('Sunset','Silver Lake',14),('Vermont','Beverly',11),('Vendome','Beverly',8),('Park','Echo Park',14),
    ('Laveta Terrace','Sunset',9),('Sunset','Douglas',15),('Western','3rd',15),('Kenmore','3rd',12),('5th','Western',8),
    ('4th','Vermont',15),('Wilshire','Hobart',9),('Wilshire','Normandie',12),('Wilshire','Alexandria',14),('Kenmore','6th',16),
    ('Shatto Pl','Wilshire',9),('Virgil','6th',15),('Normandie','8th',4),('7th','Berendo',15),('8th','Vermont',15),
    ('7th','Westmoreland',15),('Ardmore','Olympic',15),('Berendo','Olympic',18),('Rampart','Wilshire',15),('7th','Park View',15),
    ('James M Wood','Alvarado',13),('Westlake','3rd',10),('Union','7th',12),('Wilshire','Witmer',8),('7th','Bixel',33),
    ('Union','Olympic',14),('Albany','Olympic',15),('12th','Valencia',13),('Figueroa','Cesar E Chavez',15),('Hill','College',13),
    ('Spring','College',15),('New High','Ord',15),('2nd','Figueroa',18),('Hope','1st',16),('Grand','Temple',14),
    ('Figueroa','4th',15),('Grand','3rd',14),('2nd','Hill',17),('Main','1st',29),('Los Angeles','Temple',30),
    ('Broadway','3rd',23),('Spring','3rd',14),('Main','Winston',12),('3rd','San Pedro',15),('San Pedro','Winston',11),
    ('1st','Central',28),('Traction','Rose',24),('Temple','Vignes',14),('3rd','Santa Fe',20),('1st','Utah',18),
    ('5th','Hewitt',14),('Factory Pl','Alameda',19),('Willow','Mateo',19),('Industrial','Mateo',14),('Imperial','7th',19),
    ('Stanford','12th',15),('18th','San Pedro',14),('Figueroa','Pico',17),('Figueroa','11th',16),('Figueroa','9th',15),
    ('Figueroa','8th',23),('7th','Flower',29),('Hope','6th',31),('5th','Grand',23),('Pico','Flower',34),
    ('Hope','11th',29),('Hope','Olympic',22),('Grand','8th',18),('Grand','Olympic',19),('Olive','8th',29),
    ('7th','Hill',19),('Grand','14th',15),('12th','Hill',19),('Broadway','11th',19),('Broadway','9th',15),
    ('Main','8th',8),('7th','Spring',15),('Main','9th',15),('9th','Los Angeles',15),('8th','Wall',15),
    ('11th','Maple',15),('23rd','Flower',22),('Hill','Washington',20),('Grand','Washington',15),('25th','Vermont',8),
    ('Ellendale Pl','Adams',12),('Severance','Adams',15),('29th','Ellendale',19),('Hoover','29th',15),('28th','University',10),
    ('28th','Figueroa',15),('University','30th',9),('Hoover','32nd',15),('University','Hoover',14),('32nd','Figueroa',14),
    ('Figueroa','Jefferson',8),('Figueroa','McCarthy',15),('Vermont','Exposition',14);
INSERT INTO Station (ST1,ST2,DOCKS) VALUES 
    ('Broxton','Weyburn',15),('Glendon','Kinross',9),('Purdue','Santa Monica',20),('Mississippi','Sawtelle',9),('Arizona','16th',11),
    ('Barrington','National',16),('Sepulveda','National',16),('Westwood','National',11),('Rose','Overland',7),('National','Motor',15),
    ('Palms','Motor',9),('Motor','Regent',11),('Palms','Kelton',9),('Sepulveda','Palms',9),('Sepulveda','Charnock',8),
    ('Durango','Venice',11),('Bagley','Venice',17),('Venice','Hughes',14),('Venice','Motor',11),('Venice','Glendon',10),
    ('Sepulveda','Venice',17),('Venice','Sawtelle',11),('McLaughlin','Venice',13),('Venice','Inglewood',8),('Venice','Colonial',11),
    ('Venice','Beethoven',8),('Venice','Walgrove',17),('Venice','Lincoln',16),('Venice','Abbot Kinney',9),('Pacific','Venice',13),
    ('Ocean Front Walk','Venice',11),('Windward','Main',21),('Abbot Kinney','Cadiz',24),('7th','Westminster',15),('California','Lincoln',30),
    ('Rose','7th',21),('Rose','Rennie',21),('Rose','Main',23),('Ocean Front Walk','Navy',26),('Stanford','Washington',10),
    ('Washington','Abbot Kinney',16),('Alla','Maxella',12),('Maxella','Glencoe',12),('Alla','Glencoe',12),('Culver','Centinela',12),
    ('Inglewood','Braddock',11),('Inglewood','Ballona',12),('Lucerne','Sepulveda',11),('Centinela','Lucile',8),('Westlawn','Beatrice',14),
    ('McConnell','Runway',20),('Seabluff','Runway',10),('Vista Del Mar','Culver',8);
INSERT INTO Station VALUES 
    ('Lankershim','Chandler','North Hollywood Station',20),('Lankershim','McCormick','North Hollywood Plaza',9),('Sunset','Maltman','Sunset Triangle Plaza',15),
    ('Sunset','Mohawk','Mohawk Bend',10),('Wilshire','Western','Wiltern',11),('James M Wood','Western','Koreatown Plaza',24),
    ('Westlake','Wilshire','Westlake/MacArthur Park Station',15),('1st','2nd','Vista Hermosa Park',16),('Figueroa','Diamond','Figueroa Plaza',14),
    ('Alameda','Los Angeles','Union Station West Portal',30),('Vignes','Cesar E Chavez','Union Station East Portal',17),('Alameda','Bay','Row DTLA',18),
    ('Olive','6th','Pershing Square',22),('Grand','23rd','Grand/LATTC',12),('Figueroa','Martin Luther King Jr','Expo Park/LAFC',15),
    ('Charles E Young','Covel Steps','Drake Stadium',20),('Westwood Pl','Westwood Pl','Gateway Plaza',19),('Portola Pl','Portola Pl','Perloff Hall',20),
    ('Weyburn','Weyburn','Weyburn Terrace',12),('Colorado','5th','Downtown Santa Monica E Line Station',18),('Colorado','17th','17th St/SMC E Line Station',18),
    ('Exposition','Bundy','Expo/Bundy E Line Station',19),('Exposition','Sepulveda','Expo/Sepulveda E Line Station',15),('Exposition','Westwood','Westwood/Rancho Park E Line Station',19),
    ('Sawtelle','Stanwood','University Village (Sawtelle Blvd)',12),('Palms','Exposition','Palms E Line Station',14),('Playa Vista','Bay Park','Playa Vista Library',17),
    ('Ballona Creek','Culver','Toes Beach at Culver Blvd',6),('Marine','Marine','Dockweiler Beach at Imperial Hwy',13);
