CREATE TABLE Line
(
  COLOR           VARCHAR2(10),
  LETTER          VARCHAR2(1),
  MI_BUS          DOUBLE PRECISION,
  NUM_STOPS_STAT  INT,
  NUM_STOPS_STR   INT
)

INSERT INTO Line VALUES (COLOR,LETTER,MI_BUS,NUM_STOPS_STAT) VALUES ('Orange','G',17.7,17)
INSERT INTO Line VALUES ('Silver','J',38,12,31)
