CREATE TABLE Line
(
  COLOR        VARCHAR2(10),
  LETTER       VARCHAR2(1),
  MI_RAIL      DOUBLE PRECISION,
  NUM_STATIONS INT
);

CREATE TABLE Station
(
  NAME         VARCHAR2(30),
  NUM_IN_LINE  INT,
  OVERLAP      ENUM('YES','NO')
);
